version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - qdrant
    environment:
      - MONGO_URI=mongodb://root:root@mongo:27017
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  streamlit:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"